In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.append("/home/javonne/severity_or_subtype/src")
import functions_data
from dictionaries import highest_subject_id
import functions_abide
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
df=functions_data.load_pickle(filename="../data/abide_ii/phenotypic_data_asd_all.pkl")
df_autistic=functions_data.load_pickle(filename="../data/abide_ii/phenotypic_data_asd.pkl")
df_allistic=functions_data.load_pickle(filename="../data/abide_ii/phenotypic_data_all.pkl")
df_special=functions_data.load_pickle(filename="../data/abide_ii/phenotypic_data_special.pkl")

In [3]:
df.describe()

,DX_GROUP,AGE_AT_SCAN,SEX,FIQ,SRS_EDITION,SRS_VERSION,SRS_TOTAL_RAW,SRS_AWARENESS_RAW,SRS_COGNITION_RAW,SRS_COMMUNICATION_RAW,SRS_MOTIVATION_RAW,SRS_MANNERISMS_RAW,CURRENT_MED_STATUS
count,376.000000,376.000000,376.000000,375.000000,360.000000,360.000000,360.000000,332.000000,332.000000,360.000000,360.000000,360.000000,376.000000
mean,1.609043,17.428743,1.188830,111.360000,1.533333,1.327778,48.219444,7.180723,8.096386,15.688889,8.563889,8.236111,0.257979
std,0.488615,12.055044,0.391895,13.397302,0.499582,0.470057,41.467498,4.929459,8.191978,14.626945,7.428870,8.835692,0.438105
min,1.000000,8.013699,1.000000,63.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,10.045890,1.000000,104.000000,1.000000,1.000000,14.000000,3.000000,1.750000,3.000000,2.000000,1.000000,0.000000
50%,2.000000,11.816438,1.000000,113.000000,2.000000,1.000000,29.500000,6.000000,4.000000,10.000000,7.000000,4.000000,0.000000
75%,2.000000,20.000000,1.000000,120.000000,2.000000,2.000000,81.000000,11.000000,15.000000,27.000000,13.000000,14.000000,1.000000
max,2.000000,64.000000,2.000000,146.000000,2.000000,2.000000,155.000000,20.000000,31.000000,55.000000,29.000000,35.000000,1.000000

In [22]:
# Create some masks
mask_asd = df["DX_GROUP"]==1
mask_all = df["DX_GROUP"]==2
mask_younger = df["AGE_AT_SCAN "] < 16
# mask for nans
nan_counts = df.isna().sum(axis=1)
mask_nan = nan_counts <= 2

In [5]:
labels = functions_data.load_pickle(filename="../data/abide_ii/most_recent_labels.pkl")

In [6]:
df[mask_younger & mask_asd].describe()

,DX_GROUP,AGE_AT_SCAN,SEX,FIQ,SRS_EDITION,SRS_VERSION,SRS_TOTAL_RAW,SRS_AWARENESS_RAW,SRS_COGNITION_RAW,SRS_COMMUNICATION_RAW,SRS_MOTIVATION_RAW,SRS_MANNERISMS_RAW,CURRENT_MED_STATUS
count,72.0,72.000000,72.000000,71.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,72.000000
mean,1.0,10.924832,1.208333,105.352113,1.500000,1.029412,95.911765,13.205882,17.205882,32.691176,15.029412,17.779412,0.555556
std,0.0,1.945253,0.408966,15.810574,0.503718,0.170214,25.966531,3.564162,5.857917,8.938024,6.452977,6.610362,0.500391
min,1.0,8.013699,1.000000,63.000000,1.000000,1.000000,41.000000,4.000000,5.000000,17.000000,0.000000,5.000000,0.000000
25%,1.0,9.198630,1.000000,92.500000,1.000000,1.000000,76.000000,11.000000,13.000000,25.000000,11.000000,13.000000,0.000000
50%,1.0,10.786301,1.000000,107.000000,1.500000,1.000000,96.000000,13.000000,18.000000,33.500000,14.000000,17.500000,1.000000
75%,1.0,12.501027,1.000000,115.500000,2.000000,1.000000,115.250000,16.000000,21.000000,39.250000,20.000000,23.000000,1.000000
max,1.0,15.500000,2.000000,139.000000,2.000000,2.000000,155.000000,20.000000,31.000000,51.000000,28.000000,35.000000,1.000000

In [7]:
df_ya = df[mask_younger & mask_asd]

In [10]:
labels

array([0, 0, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)

In [12]:
df_ya

,SITE_ID,DX_GROUP,AGE_AT_SCAN,SEX,FIQ,SRS_EDITION,SRS_VERSION,SRS_TOTAL_RAW,SRS_AWARENESS_RAW,SRS_COGNITION_RAW,SRS_COMMUNICATION_RAW,SRS_MOTIVATION_RAW,SRS_MANNERISMS_RAW,CURRENT_MED_STATUS,cluster
SUB_ID,,,,,,,,,,,,,,,
sub-064,ABIDEII-ETH_1,1,14.750000,1,119.0,2.0,2.0,103.0,10.0,12.0,40.0,27.0,14.0,1,0
sub-065,ABIDEII-ETH_1,1,15.416667,1,119.0,2.0,2.0,61.0,8.0,8.0,23.0,17.0,5.0,1,0
sub-124,ABIDEII-KKI_1,1,8.476712,1,114.0,1.0,1.0,88.0,16.0,19.0,29.0,10.0,14.0,0,1
sub-125,ABIDEII-KKI_1,1,9.246575,1,88.0,1.0,1.0,138.0,18.0,23.0,47.0,22.0,28.0,1,1
sub-126,ABIDEII-KKI_1,1,8.646575,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sub-349,ABIDEII-TCD_1,1,12.250000,1,107.0,1.0,1.0,136.0,19.0,26.0,49.0,17.0,25.0,0,0
sub-350,ABIDEII-TCD_1,1,14.000000,1,122.0,1.0,1.0,76.0,9.0,12.0,29.0,14.0,12.0,0,0
sub-351,ABIDEII-TCD_1,1,10.750000,1,139.0,1.0,1.0,69.0,14.0,13.0,28.0,8.0,6.0,0,0
sub-352,ABIDEII-TCD_1,1,12.750000,1,120.0,1.0,1.0,105.0,13.0,19.0,42.0,12.0,19.0,0,0
sub-355,ABIDEII-TCD_1,1,10.000000,1,115.0,1.0,1.0,69.0,15.0,16.0,28.0,4.0,6.0,0,0

In [14]:
len(labels) == len(df_ya)

True

In [15]:
df_ya["cluster"]=labels

/tmp/ipykernel_10879/2549314308.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ya["cluster"]=labels

In [16]:
df_ya.head(20)

,SITE_ID,DX_GROUP,AGE_AT_SCAN,SEX,FIQ,SRS_EDITION,SRS_VERSION,SRS_TOTAL_RAW,SRS_AWARENESS_RAW,SRS_COGNITION_RAW,SRS_COMMUNICATION_RAW,SRS_MOTIVATION_RAW,SRS_MANNERISMS_RAW,CURRENT_MED_STATUS,cluster
SUB_ID,,,,,,,,,,,,,,,
sub-064,ABIDEII-ETH_1,1,14.750000,1,119.0,2.0,2.0,103.0,10.0,12.0,40.0,27.0,14.0,1,0
sub-065,ABIDEII-ETH_1,1,15.416667,1,119.0,2.0,2.0,61.0,8.0,8.0,23.0,17.0,5.0,1,0
sub-124,ABIDEII-KKI_1,1,8.476712,1,114.0,1.0,1.0,88.0,16.0,19.0,29.0,10.0,14.0,0,1
sub-125,ABIDEII-KKI_1,1,9.246575,1,88.0,1.0,1.0,138.0,18.0,23.0,47.0,22.0,28.0,1,1
sub-126,ABIDEII-KKI_1,1,8.646575,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
sub-127,ABIDEII-KKI_1,1,9.216438,2,115.0,1.0,1.0,109.0,14.0,18.0,37.0,12.0,28.0,1,1
sub-128,ABIDEII-KKI_1,1,12.789041,1,126.0,1.0,1.0,41.0,12.0,5.0,17.0,1.0,6.0,1,2
sub-129,ABIDEII-KKI_1,1,9.994521,2,115.0,1.0,1.0,114.0,17.0,22.0,39.0,14.0,22.0,1,1
sub-130,ABIDEII-KKI_1,1,9.561644,2,130.0,1.0,1.0,116.0,14.0,23.0,36.0,17.0,26.0,1,2
sub-131,ABIDEII-KKI_1,1,8.457534,1,114.0,1.0,1.0,120.0,15.0,23.0,41.0,17.0,24.0,0,1
sub-132,ABIDEII-KKI_1,1,9.331507,1,76.0,1.0,1.0,99.0,12.0,19.0,42.0,15.0,11.0,1,1
sub-133,ABIDEII-KKI_1,1,10.660274,1,90.0,1.0,1.0,63.0,11.0,15.0,21.0,8.0,8.0,1,2
sub-134,ABIDEII-KKI_1,1,8.736986,1,100.0,1.0,1.0,105.0,15.0,17.0,37.0,15.0,21.0,1,1
sub-135,ABIDEII-KKI_1,1,12.849315,1,129.0,1.0,1.0,106.0,15.0,19.0,35.0,12.0,25.0,1,1
sub-136,ABIDEII-KKI_1,1,8.095890,2,88.0,1.0,1.0,114.0,15.0,24.0,38.0,20.0,17.0,0,2
sub-137,ABIDEII-KKI_1,1,11.443836,1,110.0,1.0,1.0,91.0,15.0,14.0,32.0,13.0,17.0,1,1
sub-138,ABIDEII-KKI_1,1,8.989041,2,98.0,1.0,1.0,59.0,6.0,9.0,18.0,12.0,14.0,0,1
sub-139,ABIDEII-KKI_1,1,11.465753,1,131.0,1.0,1.0,62.0,9.0,7.0,25.0,7.0,14.0,0,1
sub-140,ABIDEII-KKI_1,1,10.542466,2,92.0,1.0,1.0,68.0,4.0,10.0,22.0,19.0,13.0,1,1
sub-141,ABIDEII-KKI_1,1,12.986301,1,114.0,1.0,1.0,63.0,13.0,9.0,22.0,9.0,10.0,0,1

In [17]:
# More masks

mask_cluster_0 = df_ya["cluster"]==0
mask_cluster_1 = df_ya["cluster"]==1
mask_cluster_2 = df_ya["cluster"]==2

In [28]:
meta_cols=["SITE_ID","DX_GROUP","AGE_AT_SCAN ","SRS_EDITION", "SRS_VERSION", "SEX", "cluster"]
meta_cols=["SITE_ID","DX_GROUP","SRS_EDITION", "SRS_VERSION", "SEX", "cluster"]

for col in df_ya.drop(meta_cols,axis=1).columns:

    # Get means and std's
    C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
    C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
    C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])
    
    ALL_TRAIT = np.array(df[mask_all & mask_nan][col])
    print("="*70)
    print("Means")
    
    print(f"The mean {col} of cluster 0 is {round(np.nanmean(C0_TRAIT),2)} ({round(np.std(C0_TRAIT[~np.isnan(C0_TRAIT)]),2)})")
    print(f"The mean {col} of cluster 1 is {round(np.nanmean(C1_TRAIT),2)} ({round(np.std(C1_TRAIT[~np.isnan(C1_TRAIT)]),2)})")
    print(f"The mean {col} of cluster 2 is {round(np.nanmean(C2_TRAIT),2)} ({round(np.std(C2_TRAIT[~np.isnan(C2_TRAIT)]),2)})")
    print(f"The mean {col} of Allistic subjects is {round(np.nanmean(ALL_TRAIT),2)} ({round(np.std(ALL_TRAIT),2)})")

    # Check for significance
    _, p_value_C0_C1 = stats.ttest_ind(C0_TRAIT[~np.isnan(C0_TRAIT)], C1_TRAIT[~np.isnan(C1_TRAIT)])
    _, p_value_C1_C2 = stats.ttest_ind(C1_TRAIT[~np.isnan(C1_TRAIT)], C2_TRAIT[~np.isnan(C2_TRAIT)])
    _, p_value_C0_C2 = stats.ttest_ind(C0_TRAIT[~np.isnan(C0_TRAIT)], C2_TRAIT[~np.isnan(C2_TRAIT)])
    
    _, p_value_ALL_C0 = stats.ttest_ind(ALL_TRAIT[~np.isnan(ALL_TRAIT)], C0_TRAIT[~np.isnan(C0_TRAIT)])
    _, p_value_ALL_C1 = stats.ttest_ind(ALL_TRAIT[~np.isnan(ALL_TRAIT)], C1_TRAIT[~np.isnan(C1_TRAIT)])
    _, p_value_ALL_C2 = stats.ttest_ind(ALL_TRAIT[~np.isnan(ALL_TRAIT)], C2_TRAIT[~np.isnan(C2_TRAIT)])


    print("="*30)
    print("AUTISTIC vs ALLISTIC")
        
    # if p_value_ALL_C0 < 0.05:
    #     print(f"Difference between ALL and C0 is statistically significant for {col} {round(p_value_ALL_C0,5)}")
    # else:
    #     print(f"Difference between ALL and C0 is NOT statistically significant for {col} {round(p_value_ALL_C0,5)}")

    # if p_value_ALL_C1 < 0.05:
    #     print(f"Difference between ALL and C1 is statistically significant for {col} {round(p_value_ALL_C1,5)}")
    # else:
    #     print(f"Difference between ALL and C1 is NOT statistically significant for {col} {round(p_value_ALL_C1,5)}")

    # if p_value_ALL_C2 < 0.05:
    #     print(f"Difference between ALL and C2 is statistically significant for {col} {round(p_value_ALL_C2,5)}")
    # else:
    #     print(f"Difference between ALL and C2 is NOT statistically significant for {col} {round(p_value_ALL_C2,5)}")

    print("="*30)
    print("INTERGROUP")
    
    if p_value_C0_C1 < 0.05:
        print(f"Difference between C0 and C1 is statistically significant for {col} {round(p_value_C0_C1,5)}")
    else:
        print(f"Difference between C0 and C1 is NOT statistically significant for {col} {round(p_value_C0_C1,5)}")

    if p_value_C1_C2 < 0.05:
        print(f"Difference between C1 and C2 is statistically significant for {col} {round(p_value_C1_C2,5)}")
    else:
        print(f"Difference between C1 and C2 is NOT statistically significant for {col} {round(p_value_C1_C2,5)}")

    if p_value_C0_C2 < 0.05:
        print(f"Difference between C0 and C2 is statistically significant for {col} {round(p_value_C0_C2,5)}")
    else:
        print(f"Difference between C0 and C2 is NOT statistically significant for {col} {round(p_value_C0_C2,5)}")

    print("="*70)

    print()

======================================================================
Means
The mean AGE_AT_SCAN  of cluster 0 is 13.05 (1.65)
The mean AGE_AT_SCAN  of cluster 1 is 10.42 (1.7)
The mean AGE_AT_SCAN  of cluster 2 is 10.34 (1.37)
The mean AGE_AT_SCAN  of Allistic subjects is 16.03 (11.56)
==============================
AUTISTIC vs ALLISTIC
==============================
INTERGROUP
Difference between C0 and C1 is statistically significant for AGE_AT_SCAN  1e-05
Difference between C1 and C2 is NOT statistically significant for AGE_AT_SCAN  0.87423
Difference between C0 and C2 is statistically significant for AGE_AT_SCAN  0.00016
======================================================================

======================================================================
Means
The mean FIQ of cluster 0 is 112.21 (13.26)
The mean FIQ of cluster 1 is 106.59 (13.61)
The mean FIQ of cluster 2 is 98.46 (19.54)
The mean FIQ of Allistic subjects is 114.74 (10.99)
==============================
AUTISTIC vs ALLISTIC
==============================
INTERGROUP
Difference between C0 and C1 is NOT statistically significant for FIQ 0.19238
Difference between C1 and C2 is NOT statistically significant for FIQ 0.10648
Difference between C0 and C2 is statistically significant for FIQ 0.0487
======================================================================

======================================================================
Means
The mean SRS_TOTAL_RAW of cluster 0 is 95.57 (24.49)
The mean SRS_TOTAL_RAW of cluster 1 is 98.24 (26.24)
The mean SRS_TOTAL_RAW of cluster 2 is 88.92 (24.33)
The mean SRS_TOTAL_RAW of Allistic subjects is 20.16 (15.07)
==============================
AUTISTIC vs ALLISTIC
==============================
INTERGROUP
Difference between C0 and C1 is NOT statistically significant for SRS_TOTAL_RAW 0.74386
Difference between C1 and C2 is NOT statistically significant for SRS_TOTAL_RAW 0.27032
Difference between C0 and C2 is NOT statistically significant for SRS_TOTAL_RAW 0.50257
======================================================================

======================================================================
Means
The mean SRS_AWARENESS_RAW of cluster 0 is 12.71 (3.3)
The mean SRS_AWARENESS_RAW of cluster 1 is 13.27 (3.6)
The mean SRS_AWARENESS_RAW of cluster 2 is 13.54 (3.52)
The mean SRS_AWARENESS_RAW of Allistic subjects is 4.51 (2.75)
==============================
AUTISTIC vs ALLISTIC
==============================
INTERGROUP
Difference between C0 and C1 is NOT statistically significant for SRS_AWARENESS_RAW 0.62064
Difference between C1 and C2 is NOT statistically significant for SRS_AWARENESS_RAW 0.81709
Difference between C0 and C2 is NOT statistically significant for SRS_AWARENESS_RAW 0.55148
======================================================================

======================================================================
Means
The mean SRS_COGNITION_RAW of cluster 0 is 17.64 (6.31)
The mean SRS_COGNITION_RAW of cluster 1 is 17.12 (5.84)
The mean SRS_COGNITION_RAW of cluster 2 is 17.0 (5.11)
The mean SRS_COGNITION_RAW of Allistic subjects is 3.19 (3.39)
==============================
AUTISTIC vs ALLISTIC
==============================
INTERGROUP
Difference between C0 and C1 is NOT statistically significant for SRS_COGNITION_RAW 0.78283
Difference between C1 and C2 is NOT statistically significant for SRS_COGNITION_RAW 0.94742
Difference between C0 and C2 is NOT statistically significant for SRS_COGNITION_RAW 0.78284
======================================================================

======================================================================
Means
The mean SRS_COMMUNICATION_RAW of cluster 0 is 34.29 (7.92)
The mean SRS_COMMUNICATION_RAW of cluster 1 is 32.95 (9.16)
The mean SRS_COMMUNICATION_RAW of cluster 2 is 30.15 (8.38)
The mean SRS_COMMUNICATION_RAW of Allistic subjects is 5.87 (5.46)
==============================
AUTISTIC vs ALLISTIC
==============================
INTERGROUP
Difference between C0 and C1 is NOT statistically significant for SRS_COMMUNICATION_RAW 0.63483
Difference between C1 and C2 is NOT statistically significant for SRS_COMMUNICATION_RAW 0.34114
Difference between C0 and C2 is NOT statistically significant for SRS_COMMUNICATION_RAW 0.21687
======================================================================

======================================================================
Means
The mean SRS_MOTIVATION_RAW of cluster 0 is 16.14 (6.53)
The mean SRS_MOTIVATION_RAW of cluster 1 is 15.46 (6.26)
The mean SRS_MOTIVATION_RAW of cluster 2 is 12.46 (6.06)
The mean SRS_MOTIVATION_RAW of Allistic subjects is 4.25 (3.72)
==============================
AUTISTIC vs ALLISTIC
==============================
INTERGROUP
Difference between C0 and C1 is NOT statistically significant for SRS_MOTIVATION_RAW 0.7348
Difference between C1 and C2 is NOT statistically significant for SRS_MOTIVATION_RAW 0.14209
Difference between C0 and C2 is NOT statistically significant for SRS_MOTIVATION_RAW 0.1574
======================================================================

======================================================================
Means
The mean SRS_MANNERISMS_RAW of cluster 0 is 14.79 (6.28)
The mean SRS_MANNERISMS_RAW of cluster 1 is 19.44 (6.1)
The mean SRS_MANNERISMS_RAW of cluster 2 is 15.77 (6.54)
The mean SRS_MANNERISMS_RAW of Allistic subjects is 2.34 (2.96)
==============================
AUTISTIC vs ALLISTIC
==============================
INTERGROUP
Difference between C0 and C1 is statistically significant for SRS_MANNERISMS_RAW 0.01997
Difference between C1 and C2 is NOT statistically significant for SRS_MANNERISMS_RAW 0.07436
Difference between C0 and C2 is NOT statistically significant for SRS_MANNERISMS_RAW 0.70463
======================================================================

======================================================================
Means
The mean CURRENT_MED_STATUS of cluster 0 is 0.14 (0.35)
The mean CURRENT_MED_STATUS of cluster 1 is 0.63 (0.48)
The mean CURRENT_MED_STATUS of cluster 2 is 0.69 (0.46)
The mean CURRENT_MED_STATUS of Allistic subjects is 0.13 (0.34)
==============================
AUTISTIC vs ALLISTIC
==============================
INTERGROUP
Difference between C0 and C1 is statistically significant for CURRENT_MED_STATUS 0.00111
Difference between C1 and C2 is NOT statistically significant for CURRENT_MED_STATUS 0.70845
Difference between C0 and C2 is statistically significant for CURRENT_MED_STATUS 0.00245
======================================================================

/tmp/ipykernel_10879/923309817.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C0_TRAIT = np.array(df_ya[mask_cluster_0 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C1_TRAIT = np.array(df_ya[mask_cluster_1 & mask_nan][col])
/tmp/ipykernel_10879/923309817.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  C2_TRAIT = np.array(df_ya[mask_cluster_2 & mask_nan][col])

In [ ]:
: